openapi: 3.0.0
info: 
  title : Netflix clone API
  description: API documentation for a Simple Netflix clone application
  version: 1.0.0
  contact:
    name: Your Name
    email: your.email@example.com
    url: https://github.com/your-username/your-repo

# TODO: fix or integrate with production url
servers:
  - url: "{protocol}://localhost:8081/api/{version}"
    description: "This is the  version of our application "
 
    variables:
      version:
        enum:
          - v1 
          - v2
      protocol:
        enum:
          - http
          - https 
      

components:
  securitySchemes:
    BasicAuth:
      type: http 
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
    cookieAuth:
      type: apiKey
      in: cookie 
      name: token

security: 
  - BasicAuth: []
  - BearerAuth: []



