export const GENRES = [
  { id: 1, name: "Action" },
  { id: 2, name: "Anime" },
  { id: 3, name: "Children & Family" },
  { id: 5, name: "Anime" },
  { id: 6, name: "Children & Family" },
  { id: 7, name: "Classic" },
  { id: 8, name: "Comedies" },
  { id: 9, name: "Documentaries" },
  { id: 10, name: "Dramas" },
  { id: 11, name: "Horror" },
  { id: 12, name: "Romantic" },
  { id: 13, name: "Sci-fi & Fantasy" },
  { id: 14, name: "Sports" },
  { id: 15, name: "Thrillers" },
];
